<a href="https://colab.research.google.com/github/Sreelakshmiamenon/Machine-learning-projects/blob/main/39_student_performance_ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
df=pd.read_csv('/content/Student_Performance (1).csv')
df

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [ ]:
df.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [ ]:
df.dtypes

Hours Studied                         int64
Previous Scores                       int64
Extracurricular Activities           object
Sleep Hours                           int64
Sample Question Papers Practiced      int64
Performance Index                   float64
dtype: object

In [ ]:
df.head()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [ ]:
df.tail()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Hours Studied                     10000 non-null  int64  
 1   Previous Scores                   10000 non-null  int64  
 2   Extracurricular Activities        10000 non-null  object 
 3   Sleep Hours                       10000 non-null  int64  
 4   Sample Question Papers Practiced  10000 non-null  int64  
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB


In [ ]:
df.describe().T

count     mean        std   min   25%  \
Hours Studied                     10000.0   4.9929   2.589309   1.0   3.0   
Previous Scores                   10000.0  69.4457  17.343152  40.0  54.0   
Sleep Hours                       10000.0   6.5306   1.695863   4.0   5.0   
Sample Question Papers Practiced  10000.0   4.5833   2.867348   0.0   2.0   
Performance Index                 10000.0  55.2248  19.212558  10.0  40.0   

                                   50%   75%    max  
Hours Studied                      5.0   7.0    9.0  
Previous Scores                   69.0  85.0   99.0  
Sleep Hours                        7.0   8.0    9.0  
Sample Question Papers Practiced   5.0   7.0    9.0  
Performance Index                 55.0  71.0  100.0

In [ ]:
df.duplicated().sum()

127

In [ ]:
df.isna().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [ ]:
#encoding
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['Extracurricular Activities'] = lab.fit_transform(df['Extracurricular Activities'])
df.head()

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0              7               99                           1            9   
1              4               82                           0            4   
2              8               51                           1            7   
3              5               52                           1            5   
4              7               75                           0            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [ ]:
x=df.iloc[:,:-1].values
x

array([[ 7, 99,  1,  9,  1],
       [ 4, 82,  0,  4,  2],
       [ 8, 51,  1,  7,  2],
       ...,
       [ 6, 83,  1,  8,  5],
       [ 9, 97,  1,  7,  0],
       [ 7, 74,  0,  8,  1]])

In [ ]:
x.ndim

2

In [ ]:
y=df.iloc[:,-1].values
y

array([91., 65., 45., ..., 74., 95., 64.])

In [ ]:
y.ndim

1

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[ 4, 99,  1,  6,  1],
       [ 6, 90,  1,  9,  3],
       [ 8, 57,  0,  6,  1],
       ...,
       [ 9, 48,  0,  7,  6],
       [ 1, 47,  0,  9,  0],
       [ 2, 46,  0,  6,  6]])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
#Model creation
ann=tf.keras.models.Sequential()  #keras is the module in tf package
#input layer

In [ ]:
# first hidden layer
ann.add(tf.keras.layers.Dense(6,activation='relu'))

In [ ]:
#second hidden layer
ann.add(tf.keras.layers.Dense(6,activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(1,activation='sigmoid'))


In [ ]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [ ]:
ann.fit(x_train,y_train,batch_size=32,epochs=500)

Epoch 1/500
219/219 [==============================] - 4s 5ms/step - loss: -165.0760 - accuracy: 0.0000e+00
Epoch 2/500
219/219 [==============================] - 1s 3ms/step - loss: -1107.7633 - accuracy: 0.0000e+00
Epoch 3/500
219/219 [==============================] - 1s 3ms/step - loss: -4001.2053 - accuracy: 0.0000e+00
Epoch 4/500
219/219 [==============================] - 0s 2ms/step - loss: -10293.5410 - accuracy: 0.0000e+00
Epoch 5/500
219/219 [==============================] - 0s 2ms/step - loss: -21178.5684 - accuracy: 0.0000e+00
Epoch 6/500
219/219 [==============================] - 0s 2ms/step - loss: -37284.7617 - accuracy: 0.0000e+00
Epoch 7/500
219/219 [==============================] - 0s 2ms/step - loss: -59249.1484 - accuracy: 0.0000e+00
Epoch 8/500
219/219 [==============================] - 0s 2ms/step - loss: -87630.8125 - accuracy: 0.0000e+00
Epoch 9/500
219/219 [==============================] - 0s 2ms/step - loss: -122755.6641 - accuracy: 0.0000e+00
Epoch 10/500


In [ ]:
ann.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 6)                 36        
                                                                 
 dense_7 (Dense)             (None, 6)                 42        
                                                                 
 dense_8 (Dense)             (None, 1)                 7         
                                                                 
Total params: 85 (340.00 Byte)
Trainable params: 85 (340.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
