<a href="https://colab.research.google.com/github/Sreelakshmiamenon/Machine-learning-projects/blob/main/41_image_prediction_CNNdemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Drive mount
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
from sklearn.svm import SVC
import numpy as np
import matplotlib.pyplot as plt
import os   #define the path of file and directory
from skimage.io import imread   #used for reading images
from sklearn.model_selection import train_test_split
from skimage.transform import resize

In [ ]:
os.listdir('/content/drive/MyDrive/Data')
#listing the directory data

['Cat', 'Dog']

In [ ]:
len(os.listdir('/content/drive/MyDrive/Data/Cat')) #length of list of directory cat

85

In [ ]:
len(os.listdir('/content/drive/MyDrive/Data/Dog')) #length of list of directory dog

68

In [ ]:
#path of cat directory is given to a variable catpath
catpath=os.path.join('/content/drive/MyDrive/Data','Cat')
for img in os.listdir(catpath):
  print(img)

cat.82.jpg
cat.67.jpg
cat.98.jpg
cat.87.jpg
cat.90.jpg
cat.64.jpg
cat.84.jpg
cat.77.jpg
cat.68.jpg
cat.89.jpg
cat.76.jpg
cat.91.jpg
cat.97.jpg
cat.44.jpg
cat.78.jpg
cat.73.jpg
cat.70.jpg
cat.79.jpg
cat.86.jpg
cat.88.jpg
cat.65.jpg
cat.40.jpg
cat.81.jpg
cat.71.jpg
cat.72.jpg
cat.99.jpg
cat.75.jpg
cat.80.jpg
cat.96.jpg
cat.83.jpg
cat.93.jpg
cat.36.jpg
cat.41.jpg
cat.116.jpg
cat.112.jpg
cat.45.jpg
cat.62.jpg
cat.113.jpg
cat.119.jpg
cat.74.jpg
cat.110.jpg
cat.46.jpg
cat.58.jpg
cat.42.jpg
cat.118.jpg
cat.54.jpg
cat.57.jpg
cat.102.jpg
cat.107.jpg
cat.38.jpg
cat.60.jpg
cat.56.jpg
cat.61.jpg
cat.39.jpg
cat.95.jpg
cat.49.jpg
cat.59.jpg
cat.52.jpg
cat.114.jpg
cat.94.jpg
cat.92.jpg
cat.101.jpg
cat.55.jpg
cat.66.jpg
cat.69.jpg
cat.35.jpg
cat.50.jpg
cat.100.jpg
cat.53.jpg
cat.37.jpg
cat.117.jpg
cat.48.jpg
cat.43.jpg
cat.47.jpg
cat.51.jpg
cat.63.jpg
cat.85.jpg
cat.111.jpg
cat.109.jpg
cat.106.jpg
cat.108.jpg
cat.115.jpg
cat.103.jpg
cat.104.jpg
cat.105.jpg


In [ ]:
dogpath=os.path.join('/content/drive/MyDrive/Data','Dog')
for img in os.listdir(dogpath):
  print(img)

dog.6.jpg
dog.49.jpg
dog.31.jpg
dog.8.jpg
dog.2.jpg
dog.23.jpg
dog.37.jpg
dog.47.jpg
dog.57.jpg
dog.22.jpg
dog.3.jpg
dog.62.jpg
dog.30.jpg
dog.7.jpg
dog.68.jpg
dog.44.jpg
dog.32.jpg
dog.67.jpg
dog.40.jpg
dog.46.jpg
dog.61.jpg
dog.36.jpg
dog.60.jpg
dog.45.jpg
dog.58.jpg
dog.51.jpg
dog.42.jpg
dog.29.jpg
dog.41.jpg
dog.38.jpg
dog.63.jpg
dog.18.jpg
dog.34.jpg
dog.64.jpg
dog.9.jpg
dog.27.jpg
dog.59.jpg
dog.48.jpg
dog.39.jpg
dog.4.jpg
dog.50.jpg
dog.28.jpg
dog.66.jpg
dog.43.jpg
dog.5.jpg
dog.53.jpg
dog.26.jpg
dog.65.jpg
dog.55.jpg
dog.12.jpg
dog.33.jpg
dog.11.jpg
dog.15.jpg
dog.24.jpg
dog.21.jpg
dog.16.jpg
dog.14.jpg
dog.54.jpg
dog.20.jpg
dog.35.jpg
dog.17.jpg
dog.19.jpg
dog.56.jpg
dog.1.jpg
dog.13.jpg
dog.52.jpg
dog.10.jpg
dog.25.jpg


In [ ]:
flat_data_arr=[] # Used for collecting input data
target_arr=[] # Used for collecting output data
categories=['Cat','Dog']
datadir='/content/drive/MyDrive/Data'

In [ ]:
for i in categories: #Cat
  print("Loading categories")
  path=os.path.join(datadir,i) #/content/drive/MyDrive/Data,Cat
  for img in os.listdir(path): #for j in os.listdir(path):
    img_arr=imread(os.path.join(path,img)) # imread(os.path.join(path,img))
    img_resize=resize(img_arr,(150,150,3)) #RGB
    flat_data_arr.append(img_resize.flatten())
    target_arr.append(categories.index(i)) # 0 ==> cat  1 ==> dog
  print("Loaded completely",i)

Loading categories
Loaded completely Cat
Loading categories
Loaded completely Dog


In [ ]:
flat_data=np.array(flat_data_arr)
target_data= np.array(target_arr)
df=pd.DataFrame(flat_data)
df

0         1         2         3         4         5         6      \
0    0.478295  0.474374  0.497903  0.477381  0.473460  0.496989  0.491041   
1    0.746801  0.664834  0.570610  0.768159  0.669622  0.570784  0.766071   
2    0.039443  0.035538  0.015258  0.036979  0.033074  0.013246  0.031539   
3    0.094118  0.094118  0.086275  0.094118  0.094118  0.086275  0.094118   
4    0.267715  0.216751  0.142193  0.271836  0.223559  0.140938  0.275575   
..        ...       ...       ...       ...       ...       ...       ...   
148  0.768130  0.691507  0.619205  0.562160  0.443307  0.340889  0.623372   
149  0.615686  0.647059  0.658824  0.615686  0.647059  0.658824  0.615686   
150  0.197998  0.201073  0.142554  0.200468  0.174041  0.135699  0.225444   
151  0.562609  0.466070  0.253184  0.531096  0.417403  0.202458  0.519534   
152  0.008784  0.081797  0.003346  0.041734  0.105453  0.029321  0.048398   

        7         8         9      ...     67490     67491     67492  \
0    0.487119  0.510649  0.499533  ...  0.544947  0.576333  0.541039   
1    0.672205  0.569096  0.722603  ...  0.414763  0.622804  0.523688   
2    0.027634  0.007980  0.029253  ...  0.055645  0.121042  0.123941   
3    0.094118  0.086275  0.094117  ...  0.413832  0.417687  0.416508   
4    0.228515  0.139966  0.278628  ...  0.149317  0.210044  0.202201   
..        ...       ...       ...  ...       ...       ...       ...   
148  0.472422  0.342538  0.606955  ...  0.908014  0.953688  0.958069   
149  0.647059  0.658824  0.615648  ...  0.154498  0.376526  0.085354   
150  0.176508  0.160004  0.222726  ...  0.044325  0.075294  0.118756   
151  0.393667  0.170831  0.488835  ...  0.310426  0.389573  0.366044   
152  0.092893  0.028838  0.081621  ...  0.042053  0.384837  0.333710   

        67493     67494     67495     67496     67497     67498     67499  
0    0.544960  0.562095  0.526801  0.530722  0.541868  0.506574  0.510496  
1    0.484664  0.575169  0.504724  0.476907  0.572680  0.513406  0.485966  
2    0.080575  0.145913  0.145928  0.098878  0.155355  0.155355  0.108296  
3    0.406373  0.387455  0.390984  0.381789  0.370306  0.371310  0.369780  
4    0.155142  0.201097  0.193254  0.146195  0.200142  0.192299  0.145240  
..        ...       ...       ...       ...       ...       ...       ...  
148  0.897416  0.957814  0.962249  0.901571  0.950053  0.954488  0.893809  
149  0.136334  0.392032  0.101926  0.152860  0.405295  0.116949  0.167004  
150  0.027206  0.200934  0.184395  0.108955  0.400372  0.305795  0.248824  
151  0.318985  0.392066  0.368537  0.321478  0.393571  0.370042  0.322983  
152  0.030124  0.388362  0.344401  0.031503  0.377621  0.327669  0.020758  

[153 rows x 67500 columns]

In [ ]:
df.shape #153=68+85    67500=150*150*3

(153, 67500)

In [ ]:
df['Target']=target_data
df.shape

(153, 67501)

Splitting x and y

In [ ]:
x=df.iloc[:,:-1].values
x

array([[0.47829514, 0.47437357, 0.49790298, ..., 0.54186833, 0.50657421,
        0.51049578],
       [0.74680098, 0.66483396, 0.5706102 , ..., 0.57267973, 0.51340612,
        0.48596613],
       [0.03944343, 0.0355384 , 0.01525794, ..., 0.15535502, 0.15535502,
        0.1082962 ],
       ...,
       [0.19799776, 0.20107267, 0.1425542 , ..., 0.40037223, 0.30579471,
        0.24882438],
       [0.56260885, 0.46606989, 0.25318399, ..., 0.39357094, 0.37004153,
        0.3229827 ],
       [0.0087841 , 0.08179658, 0.00334578, ..., 0.37762124, 0.32766867,
        0.02075849]])

In [ ]:
y=df.iloc[:,-1].values
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[0.05863629, 0.11670326, 0.18192382, ..., 0.40804391, 0.31392626,
        0.20479499],
       [0.84878496, 0.82525555, 0.77819672, ..., 0.84478071, 0.81986949,
        0.70555633],
       [0.28247995, 0.1765976 , 0.14914662, ..., 0.54534295, 0.58101679,
        0.62200242],
       ...,
       [0.63296216, 0.49178569, 0.4290406 , ..., 0.610482  , 0.12481651,
        0.24752336],
       [0.16177408, 0.09411126, 0.140884  , ..., 0.10271019, 0.06154931,
        0.0712269 ],
       [0.56779476, 0.74302232, 0.53662867, ..., 0.26641727, 0.1879859 ,
        0.18406433]])

In [ ]:
x_test

array([[0.40836579, 0.37699324, 0.33385599, ..., 0.85035797, 0.7091815 ,
        0.16581395],
       [0.11764706, 0.12548947, 0.11683148, ..., 0.15036089, 0.21702755,
        0.24447854],
       [0.62360928, 0.76723003, 0.75071565, ..., 0.39211864, 0.32680695,
        0.20450557],
       ...,
       [0.37947203, 0.52849241, 0.19430685, ..., 0.34117588, 0.559507  ,
        0.11743496],
       [0.26771534, 0.21675126, 0.14219251, ..., 0.20014238, 0.19229925,
        0.14524042],
       [0.26884764, 0.27276921, 0.25316136, ..., 0.30075834, 0.22624853,
        0.167425  ]])

In [ ]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1])

In [ ]:
y_test

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0])

In [ ]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
score=accuracy_score(y_test,y_pred)
score        #accuracy is less due to less size of training and testing data

0.6086956521739131

In [ ]:
matrix=confusion_matrix(y_test,y_pred)
matrix

array([[18, 11],
       [ 7, 10]])

In [ ]:
path1='/content/cat_1.jpg'
img1=imread(path1)   #to read image
img1=resize(img1,(150,150,3)).flatten().reshape(1,-1)   #resizing,change to 1D,reshaping
model.predict(img1)

array([0])

In [ ]:
path2='/content/dog_2.jpg'
img2=imread(path2)
img2=resize(img2,(150,150,3)).flatten().reshape(1,-1)
model.predict(img2)

array([1])