<a href="https://colab.research.google.com/github/Sreelakshmiamenon/Machine-learning-projects/blob/main/9_Diabetes_prediction_SupervisedML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/Naive-Bayes-Classification-Data.csv')
df

glucose  bloodpressure  diabetes
0         40             85         0
1         40             92         0
2         45             63         1
3         45             80         0
4         40             73         1
..       ...            ...       ...
990       45             87         0
991       40             83         0
992       40             83         0
993       40             60         1
994       45             82         0

[995 rows x 3 columns]

In [ ]:
df.head()

glucose  bloodpressure  diabetes
0       40             85         0
1       40             92         0
2       45             63         1
3       45             80         0
4       40             73         1

In [ ]:
df.tail()

glucose  bloodpressure  diabetes
990       45             87         0
991       40             83         0
992       40             83         0
993       40             60         1
994       45             82         0

In [ ]:
df.dtypes

glucose          int64
bloodpressure    int64
diabetes         int64
dtype: object

In [ ]:
df.columns

Index(['glucose', 'bloodpressure', 'diabetes'], dtype='object')

In [ ]:
df.shape

(995, 3)

In [ ]:
df.isna().sum()

glucose          0
bloodpressure    0
diabetes         0
dtype: int64

In [ ]:
x=df.iloc[:,:-1].values
x

array([[40, 85],
       [40, 92],
       [45, 63],
       ...,
       [40, 83],
       [40, 60],
       [45, 82]])

In [ ]:
x.ndim

2

In [ ]:
y=df.iloc[:,-1].values
y

array([0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,

In [ ]:
y.ndim

1

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[40, 82],
       [45, 82],
       [45, 85],
       ...,
       [35, 78],
       [40, 93],
       [45, 95]])

In [ ]:
x_test

array([[ 40,  70],
       [ 40,  75],
       [ 45,  65],
       [ 45,  93],
       [ 45,  88],
       [ 40,  85],
       [ 40,  75],
       [ 40,  85],
       [ 40,  87],
       [ 50,  73],
       [ 50,  92],
       [ 45,  82],
       [ 45,  93],
       [ 45,  80],
       [ 45,  93],
       [ 55,  70],
       [ 45,  77],
       [ 60,  65],
       [ 40,  73],
       [ 45,  92],
       [ 45,  83],
       [ 40,  68],
       [ 60,  75],
       [ 45,  88],
       [ 40,  88],
       [ 45,  97],
       [ 50,  73],
       [ 35,  63],
       [ 40,  87],
       [ 40,  83],
       [ 40, 100],
       [ 55,  73],
       [ 40,  88],
       [ 35,  75],
       [ 45,  83],
       [ 45,  70],
       [ 50,  67],
       [ 45,  88],
       [ 45,  85],
       [ 45,  85],
       [ 50,  65],
       [ 45,  88],
       [ 45,  87],
       [ 50,  92],
       [ 45,  88],
       [ 45,  98],
       [ 45,  77],
       [ 40,  67],
       [ 35,  73],
       [ 50,  63],
       [ 50,  88],
       [ 45,  78],
       [ 45,

In [ ]:
y_train

array([1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,

In [ ]:
y_test

array([1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[-0.65627227,  0.27406459],
       [ 0.11269322,  0.27406459],
       [ 0.11269322,  0.59773363],
       ...,
       [-1.42523775, -0.15749413],
       [-0.65627227,  1.46085108],
       [ 0.11269322,  1.67663044]])

In [ ]:
x_test

array([[-0.65627227, -1.02061158],
       [-0.65627227, -0.48116317],
       [ 0.11269322, -1.56005998],
       [ 0.11269322,  1.46085108],
       [ 0.11269322,  0.92140267],
       [-0.65627227,  0.59773363],
       [-0.65627227, -0.48116317],
       [-0.65627227,  0.59773363],
       [-0.65627227,  0.81351299],
       [ 0.8816587 , -0.69694253],
       [ 0.8816587 ,  1.3529614 ],
       [ 0.11269322,  0.27406459],
       [ 0.11269322,  1.46085108],
       [ 0.11269322,  0.05828523],
       [ 0.11269322,  1.46085108],
       [ 1.65062418, -1.02061158],
       [ 0.11269322, -0.26538381],
       [ 2.41958967, -1.56005998],
       [-0.65627227, -0.69694253],
       [ 0.11269322,  1.3529614 ],
       [ 0.11269322,  0.38195427],
       [-0.65627227, -1.23639094],
       [ 2.41958967, -0.48116317],
       [ 0.11269322,  0.92140267],
       [-0.65627227,  0.92140267],
       [ 0.11269322,  1.8924098 ],
       [ 0.8816587 , -0.69694253],
       [-1.42523775, -1.77583934],
       [-0.65627227,

In [ ]:
#USE FOR LOOP FOR DOING 3 ALGORITHMS TOGETHER
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score
k_model=KNeighborsClassifier()
n_model=GaussianNB()
s_model=SVC()

lst_model=[k_model,n_model,s_model]

In [ ]:
for i in lst_model:
  print("Model name is: ",i)
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print("********************************")
  print(confusion_matrix(y_test,y_pred))
  print("Accuracy score................")
  print(accuracy_score(y_test,y_pred))

Model name is:  KNeighborsClassifier()
********************************
[[132   8]
 [ 10 149]]
Accuracy score................
0.939799331103679
Model name is:  GaussianNB()
********************************
[[130  10]
 [ 10 149]]
Accuracy score................
0.9331103678929766
Model name is:  SVC()
********************************
[[130  10]
 [  9 150]]
Accuracy score................
0.9364548494983278


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.93      0.93       140
           1       0.94      0.94      0.94       159

    accuracy                           0.94       299
   macro avg       0.94      0.94      0.94       299
weighted avg       0.94      0.94      0.94       299

